### ISSUE TITLE
What are we needing to do?

### ISSUE THREAD

**Issue by loganvane** [coryell1287/utility#1]
in the post you had said that the content filters where set to low for the height?

**Comment by coryell1287** [comment]
I have the max-height of the panels set to 500px, so that the animation
will flow smoothly. But setting the max-height to 500px truncates the
content. If you were to add more content, the panel will not enlarge to
accommodate it. Typically, in jQuery, you can add as much content to the
panels and it will enlarge for it.  In this version the same behavior has
to be done in JavaScript.

__________________________________________________________________
The struggle you're in today is developing the strength you need
 for tomorrow.

[image: http://pakwired.com/wp-content/uploads/2015/01/Success-loading.jpg]

**Comment by coryell1287** [comment]
I have the max-height of the panels set to 500px, so that the animation will flow smoothly. But setting the max-height to 500px truncates the content. If you were to add more content, the panel will not enlarge to accommodate it. Typically, in jQuery, you can add as much content to the panels and it will enlarge for it.  In this version the same behavior has to be done in JavaScript.
